# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/azurelinux/base/core:3.0 as installer

RUN tdnf -y update \
 && tdnf install -y dnf \
 && mkdir /staging \
 && dnf install -y --installroot /staging --release=3.0 python3 python3-pip

FROM mcr.microsoft.com/azurelinux/distroless/base:3.0 as final

COPY --from=installer /staging/ /

ENV PYTHONUNBUFFERED=true TILESRV=/tilesrv

COPY requirements-tilesrv.txt gentiles.py $TILESRV/

RUN pip3 install -r $TILESRV/requirements-tilesrv.txt

ENTRYPOINT python3 /tilesrv/gentiles.py --verbose