# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM ubuntu:latest as final

ENV IMPOSM_BINARY_RELEASE=0.14.2

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y curl wget postgresql-client-common postgresql-client-16 jq sysstat \
    && apt-get install -y python3 python3-pip python3-setuptools python3-venv

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN mkdir -p /ingest/imposm3 \
    && wget -q -O - https://github.com/omniscale/imposm3/releases/download/v$IMPOSM_BINARY_RELEASE/imposm-$IMPOSM_BINARY_RELEASE-linux-x86-64.tar.gz | tar -xz --strip-components=1 -C /ingest/imposm3

ENV PYTHONUNBUFFERED=true INGEST=/ingest

COPY requirements.txt ingest_simple.py tilefunc.sql postgis-vt-util.sql config.json mapping.yml /ingest/
COPY extracts/ /ingest/extracts/

# Create venv and install deps
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -r $INGEST/requirements.txt

# Ensure venv Python is default for CMD and any shell-in debugging
ENV PATH="/opt/venv/bin:$PATH"

CMD python3 /ingest/ingest_simple.py --imposm /ingest/imposm3/imposm --mapping /ingest/mapping.yml --extracts /ingest/extracts/extracts-${GEN_REGIONS}.json --basedir ${TILES} --verbose --inc --config /ingest/config.json