# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM mcr.microsoft.com/azurelinux/base/core:3.0 as installer

RUN tdnf -y update \
 && tdnf install -y dnf \
 && mkdir /staging \
 && dnf install -y --installroot /staging --release=3.0 python3 python3-pip python3-setuptools

FROM mcr.microsoft.com/azurelinux/base/core:3.0 as imposm

ENV IMPOSM_BINARY_RELEASE=0.14.2

RUN tdnf -y update \
 && tdnf install -y ca-certificates-microsoft wget tar gzip \
 && mkdir -p /ingest/imposm3 \
 && wget -q -O - https://github.com/omniscale/imposm3/releases/download/v$IMPOSM_BINARY_RELEASE/imposm-$IMPOSM_BINARY_RELEASE-linux-x86-64.tar.gz | tar -xz --strip-components=1 -C /ingest/imposm3

FROM mcr.microsoft.com/azurelinux/distroless/base:3.0 as final

ENV PYTHONUNBUFFERED=true INGEST=/ingest TILES=/tiles

COPY --from=imposm /ingest/ $INGEST/
COPY --from=installer /staging/ /

COPY ../ingest/config.json ../ingest/mapping.yml $INGEST/
COPY requirements-diffs.txt ingest_diffs.py $INGEST/

RUN /usr/bin/pip3 install -r $INGEST/requirements-diffs.txt

CMD python3 $INGEST/ingest_diffs.py --imposm $INGEST/imposm3/imposm --mapping $INGEST/mapping.yml --basedir $TILES --verbose --config $INGEST/config.json