#cloud-config
package_update: true
packages:
  - curl
  - wget
  - unzip
  - postgresql-client-common
  - postgresql-client-16
  - jq
  - sysstat
  - python3
  - python3-pip
  - python3-setuptools
  - python3-venv

write_files:
  - path: /opt/ingest/files.tgz
    encoding: b64
    content: |
      {{FILES_TGZ}}
  - path: /opt/ingest/env.sh
    permissions: '0700'
    content: |
      #!/bin/bash
      # Environment variables for the ingest job
      export IMPOSM_BINARY_RELEASE=0.14.2
      export POSTGIS_USER=pgadmin
      export POSTGIS_DBNAME=osm
      export POSTGIS_PORT=5432
      export PYTHONUNBUFFERED=true
      export INGEST=/opt/ingest
      export TILES=/mnt
      {{ENV_BLOCK}}
  - path: /opt/ingest/setup.sh
    permissions: '0700'
    content: |
      #!/bin/bash
      set -euo pipefail
      . /opt/ingest/env.sh

      mkdir -p ${INGEST}/logs

      # Install Azure CLI
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Login
      az login --identity

      mkdir -p ${INGEST}/imposm3
      wget -q -O - https://github.com/omniscale/imposm3/releases/download/v$IMPOSM_BINARY_RELEASE/imposm-$IMPOSM_BINARY_RELEASE-linux-x86-64.tar.gz | tar -xz --strip-components=1 -C ${INGEST}/imposm3

      # Extract the files
      tar -xzf /opt/ingest/files.tgz -C ${INGEST}

      # Create venv and install deps
      python3 -m venv ${INGEST}/venv && ${INGEST}/venv/bin/pip install --no-cache-dir -r $INGEST/requirements.txt

  - path: /opt/ingest/ingest.sh
    permissions: '0700'
    content: |
      #!/bin/bash
      # No pipefail, as we want to still continue if the ingest fails
      . /opt/ingest/env.sh

      # Ensure venv Python is default for CMD and any shell-in debugging
      PATH="/opt/ingest/venv/bin:$PATH"

      LOGFILE="${INGEST}/logs/ingest_$(date +%Y%m%d_%H%M%S).log"

      python3 -u ${INGEST}/ingest_simple.py --imposm ${INGEST}/imposm3/imposm --mapping ${INGEST}/mapping.yml --extracts ${INGEST}/extracts/extracts-${GEN_REGIONS}.json \
        --basedir ${TILES} --verbose --config ${INGEST}/config.json 2>&1 | \
        sed -uE 's/^\[([0-9]{4}-[0-9]{2}-[0-9]{2})T([0-9]{2}:[0-9]{2}:[0-9]{2})Z\]/\1 \2/' > ${LOGFILE}

      # Sleep for 30 seconds so logs are flushed
      #sleep 30

      # Shutdown after completion
      # Actually, should really downsize the vmss instead
      #sudo shutdown -h now

runcmd:
  - [ bash, /opt/ingest/setup.sh ]
  - [ chown, -R, azureuser:azureuser, /opt/ingest ]
  - [ chmod, '0777', /mnt ]
